#define APPMSG_METHOD_KEY 1
#define APPMSG_COUNT_KEY 2
#define APPMSG_INDEX_KEY 3
#define APPMSG_BULB_STATE_KEY 4
#define APPMSG_LABEL_KEY 5
#define APPMSG_COLOR_TYPE_KEY 6
#define APPMSG_COLOR_INDEX_KEY 7

#define APPMSG_METHOD_GET_BULBS "get_bulbs"
#define APPMSG_METHOD_BEGIN_RELOAD_BULBS "begin_reload_bulbs"
#define APPMSG_METHOD_RECEIVE_BULB "bulb"
#define APPMSG_METHOD_END_RELOAD_BULBS "end_reload_bulbs"
#define APPMSG_METHOD_GET_COLORS "get_colors"
#define APPMSG_METHOD_BEGIN_RELOAD_COLORS "begin_reload_colors"
#define APPMSG_METHOD_RECEIVE_COLOR "color"
#define APPMSG_METHOD_END_RELOAD_COLORS "end_reload_colors"
#define APPMSG_METHOD_UPDATE_BULB_STATE "bulb_state"
#define APPMSG_METHOD_UPDATE_BULB_COLOR "bulb_color"

#define APPMSG_COLOR_TYPE_CUSTOM 1
#define APPMSG_COLOR_TYPE_DEFAULT 2